### ISSUE TITLE
wrong json values in the links_data

### ISSUE THREAD

**Issue by romanchyla** [adsabs/ADSimportpipeline#85] opened 2015-01-06 00:00 UTC
the following bibcode 2014MPEC....W...19A 

had this invalid string

{"title":"HREF="http://minorplanetcenter.org/mpec/K14/K14W19.html">Available from the Minor Planet Center.</A>", "type":"priv", "instances":"", "access":""}

**Comment by vsudilov** [comment] 2015-02-25 17:54
Here's the entry in the database, coming directly from ADSexports:

	{
		"origin" : null,
		"count" : null,
		"title" : "HREF=\"http://minorplanetcenter.org/mpec/K14/K14W19.html\">Available from the Minor Planet Center.</A>",
		"url" : "<A",
		"access" : null,
		"type" : "priv"
	},


Closing because the code is working as intended, the data itself is dirty.

**Closed by vsudilov** 2015-02-25 17:54 UTC
