### ISSUE TITLE
Incorrect handling of grants elements in SolrUpdater.py

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/ADSimportpipeline#84] opened 2015-01-01 20:49 UTC
Currently we have several records failing to index into SOLR due to the following exception:
```
ERROR   9904 [12/31/2014 19:32:31]:     2012ApJ...749L..28V: Traceback (most recent call last):
  File "/proj.adsx/ADSimportpipeline/pipeline/workers.py", line 99, in on_message
    result = json.dumps(self.strategies[producer]([content]))
  File "/proj.adsx/ADSimportpipeline/pipeline/../lib/SolrUpdater.py", line 653, in solrUpdate
    r = SolrAdapter.adapt(record)
  File "/proj.adsx/ADSimportpipeline/pipeline/../lib/SolrUpdater.py", line 574, in adapt
    D = eval('cls._%s' % k)(ADS_record)
  File "/proj.adsx/ADSimportpipeline/pipeline/../lib/SolrUpdater.py", line 393, in _grant
    for grant in ADS_record.get('adsdata',{}).get('grants',{}):
TypeError: 'NoneType' object is not iterable
```
The function in question is this:
```
  @staticmethod
  def _grant(ADS_record):
    result = []
    for grant in ADS_record.get('adsdata',{}).get('grants',{}):
      result.append(grant['agency'])
      result.append(grant['grant'])
    return {'grant': result}
```

The problem I spotted is that the for statement should really be:

    for grant in ADS_record.get('adsdata',{}).get('grants',[]):

i.e. 'grants' is an array not a dict.  I'm still not sure why the records with one element in the grants array make it while the others don't.  See example below.

```
# this one is ingested properly
> d1 = db.docs.findOne({'_id': '1975ICRC....9.3193D'})
> d1.grants
[ { "agency" : "NASA", "grant" : "NCC5675" } ]

# this one isn't
> d = db.docs.findOne({'_id': '2012ApJ...749L..28V'})
> d.grants
[
	{
		"agency" : "NASA-HQ",
		"grant" : "NNX08AR22G"
	},
	{
		"agency" : "NASA-HQ",
		"grant" : "NNX08AR22G"
	},
	{
		"agency" : "NASA-HQ",
		"grant" : "NNX08AR22G"
	}
]
```

**Comment by vsudilov** [comment] 2015-01-01 21:02
`for grant in ADS_record.get('adsdata',{}).get('grants',[])` is functionally equivalent to for grant in `ADS_record.get('adsdata',{}).get('grants',{}):`, although I agree the former is clearer

**Comment by vsudilov** [comment] 2015-01-01 21:03
Here is the data in mongo for that record:

    [
	{
		"agency" : "NASA-HQ",
		"grant" : "NNX08AR22G"
	},
	{
		"agency" : "NASA-HQ",
		"grant" : "NNX08AR22G"
	},
	{
		"agency" : "NASA-HQ",
		"grant" : "NNX08AR22G"
	}
    ]

**Comment by vsudilov** [comment] 2015-01-01 21:04
This is an adsdata issue; closing

**Closed by vsudilov** 2015-01-01 21:04 UTC

**Comment by aaccomazzi** [comment] 2015-01-01 21:11
What's in adsdata is correct, so why are we closing?

**Comment by vsudilov** [comment] 2015-01-01 21:14
Because I don't see any problems. The code is working as intended; pushing this record manually does indeed add it to Solr. 

I think this record made it into the error log because the ADS_data data structure was empty, i.e. no info was pulled from adsdata.
